#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

DYLIB_URL="https://f3a5dqxez3.ufs.sh/f/ijk9xZzvhn3rxlHVrDAxRQJ9o3TnX65LaGyPvFWY7lBCu1Md"
MODULES_URL="https://f3a5dqxez3.ufs.sh/f/ijk9xZzvhn3rRLgqCJ6EwKLWJ0ADYbMyxP8H6QpokZ7F1aiu"
UI_URL="https://f3a5dqxez3.ufs.sh/f/ijk9xZzvhn3rD2IKHTvR2QK1iVgakWyNDMPsXvcA9eG8xIHn"

spinner() {
    local pid=$!
    local delay=0.1
    local spinstr='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
    local i=0
    while ps -p $pid &>/dev/null; do
        printf "\r${CYAN}[${spinstr:i++%${#spinstr}:1}] ${1}...${NC} "
        sleep $delay
    done

    wait $pid 2>/dev/null
    printf "\r${GREEN}[*] ${1} - done${NC}\n"
}

main() {
    clear
    echo -e "${CYAN}[ Opiumware Global Install Script | @norbyv1 && @tufflodestone ]${NC}"
    echo -e "${CYAN}----------------------------------------------------------${NC}"
    spinner "Fetching version information"
    json=$(curl -s "https://clientsettingscdn.roblox.com/v2/client-version/MacPlayer")
    local version=$(echo "$json" | grep -o '"clientVersionUpload":"[^"]*' | grep -o '[^"]*$')
    if [ "$version" != "version-d0644711edef4361" ]; then
        echo -e "${RED}Opiumware has not yet updated to the latest version of Roblox ($version); aborting installation!${NC}"
        exit 1
    fi
    if pgrep -x "RobloxPlayer" > /dev/null; then
        pkill -9 RobloxPlayer
    fi
    test -d "/Applications/Roblox.app" && rm -rf "/Applications/Roblox.app"
    test -d "/Applications/Opiumware.app" && rm -rf "/Applications/Opiumware.app"
    (curl "https://setup.rbxcdn.com/mac/$version-RobloxPlayer.zip" -o "./RobloxPlayer.zip") & spinner "Downloading Roblox - ($version)"
    wait & spinner "Installing Roblox"
    unzip -o -q "./RobloxPlayer.zip"
    mv ./RobloxPlayer.app /Applications/Roblox.app
    rm ./RobloxPlayer.zip
    xattr -cr /Applications/Roblox.app
    (curl "$DYLIB_URL" -o "./libSystem.zip" && unzip -o -q "./libSystem.zip" && mv ./libSystem.dylib /Applications/Roblox.app/Contents/Resources/libSystem.dylib && curl -L "$MODULES_URL" -o modules.zip && unzip -o modules.zip) & spinner "Downloading modules"
    wait & spinner "Installing modules"
    spinner "Modifying client"
    ./Resources/Patcher "/Applications/Roblox.app/Contents/Resources/libSystem.dylib" "/Applications/Roblox.app/Contents/MacOS/libmimalloc.3.dylib" --strip-codesig --all-yes
    mv "/Applications/Roblox.app/Contents/MacOS/libmimalloc.3.dylib_patched" "/Applications/Roblox.app/Contents/MacOS/libmimalloc.3.dylib"
    codesign --force --deep --sign - /Applications/Roblox.app
    spinner "Downloading interface assets"
    curl -L "$UI_URL" -o "./OpiumwareUI.zip"
    unzip -o -q "./OpiumwareUI.zip"
    rm -rf ~/Opiumware/modules/latest.json ~/Opiumware/modules/luau-lsp ~/Opiumware/modules/Server
    mkdir -p ~/Opiumware/{workspace,autoexec,themes,modules,modules/Server,modules/luau-lsp}
    mv -f Resources/Server ~/Opiumware/modules/Server/server
    mv -f Resources/luau-lsp ~/Opiumware/modules/luau-lsp/luau-lsp
    mv -f ./Opiumware.app /Applications/Opiumware.app
    rm -rf Resources/Patcher __MACOSX Resources libSystem.zip modules.zip OpiumwareUI.zip
    rm -rf /Applications/Roblox.app/Contents/MacOS/RobloxPlayerInstaller.app >/dev/null 2>&1
    echo -e "${GREEN}Enjoy the Opiumware experience! Please report bugs, issues or crashes that you discover.${NC}"
    open /Applications/Roblox.app
    open /Applications/Opiumware.app
    exit
}

main
