#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

DYLIB_URL="https://f3a5dqxez3.ufs.sh/f/ijk9xZzvhn3rtEbpDr4iXmsI14v85ECV2NA93aGlBSjcZgn6"
MODULES_URL="https://f3a5dqxez3.ufs.sh/f/ijk9xZzvhn3rRLgqCJ6EwKLWJ0ADYbMyxP8H6QpokZ7F1aiu"
UI_URL="https://f3a5dqxez3.ufs.sh/f/ijk9xZzvhn3rD2IKHTvR2QK1iVgakWyNDMPsXvcA9eG8xIHn"

spinner() {
    local pid=$!
    local delay=0.1
    local spinstr='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
    local i=0
    while ps -p $pid &>/dev/null; do
        printf "\r${CYAN}[${spinstr:i++%${#spinstr}:1}] ${1}...${NC} "
        sleep $delay
    done

    wait $pid 2>/dev/null
    printf "\r${GREEN}[*] ${1} - done${NC}\n"
}

main() {
    clear
    echo -e "${CYAN}[ Opiumware Local Install Script | @norbyv1 && @tufflodestone ]${NC}"
    echo -e "${CYAN}----------------------------------------------------------${NC}"

    mkdir -p "$HOME/Applications"

    spinner "Fetching version information"
    json=$(curl -s "https://clientsettingscdn.roblox.com/v2/client-version/MacPlayer")
    local version=$(echo "$json" | grep -o '"clientVersionUpload":"[^"]*' | grep -o '[^"]*$')
    killall -9 RobloxPlayer &>/dev/null
    killall -9 Opiumware &>/dev/null
    test -d "$HOME/Applications/Roblox.app" && rm -rf "$HOME/Applications/Roblox.app"
    test -d "$HOME/Applications/Opiumware.app" && rm -rf "$HOME/Applications/Opiumware.app"
    if [ "$version" == "version-01a477dd52194f10" ]; then
        curl -s "https://raw.githubusercontent.com/norbyv1/OpiumwareInstall/main/lpreupd" | bash
        exit 0
    fi
    (curl "https://setup.rbxcdn.com/mac/$version-RobloxPlayer.zip" -o "./RobloxPlayer.zip") & spinner "Downloading Roblox - ($version)"
    wait & spinner "Installing Roblox"
    unzip -o -q "./RobloxPlayer.zip"
    mv ./RobloxPlayer.app "$HOME/Applications/Roblox.app"
    rm ./RobloxPlayer.zip
    xattr -cr "$HOME/Applications/Roblox.app"
    (curl "$DYLIB_URL" -o "./libSystem.zip" && unzip -o -q "./libSystem.zip" && mv ./libSystem.dylib "$HOME/Applications/Roblox.app/Contents/Resources/libSystem.dylib" && curl -L "$MODULES_URL" -o modules.zip && unzip -o -q modules.zip) & spinner "Downloading modules"
    wait & spinner "Installing modules"
    spinner "Modifying client"
    ./Resources/Patcher "$HOME/Applications/Roblox.app/Contents/Resources/libSystem.dylib" "$HOME/Applications/Roblox.app/Contents/MacOS/libmimalloc.3.dylib" --strip-codesig --all-yes
    mv "$HOME/Applications/Roblox.app/Contents/MacOS/libmimalloc.3.dylib_patched" "$HOME/Applications/Roblox.app/Contents/MacOS/libmimalloc.3.dylib"
    codesign --force --deep --sign - "$HOME/Applications/Roblox.app"
    spinner "Downloading interface assets"
    curl -L "$UI_URL" -o "./OpiumwareUI.zip"
    unzip -o -q "./OpiumwareUI.zip"
    rm -rf "$HOME/Opiumware/modules/latest.json" "$HOME/Opiumware/modules/luau-lsp" "$HOME/Opiumware/modules/Server"
    mkdir -p "$HOME/Opiumware"/{workspace,autoexec,themes,modules,modules/Server,modules/luau-lsp}
    mv -f Resources/Server "$HOME/Opiumware/modules/Server/server"
    mv -f Resources/luau-lsp "$HOME/Opiumware/modules/luau-lsp/luau-lsp"
    mv -f ./Opiumware.app "$HOME/Applications/Opiumware.app"
    rm -rf Resources/Patcher __MACOSX Resources libSystem.zip modules.zip OpiumwareUI.zip
    rm -rf "$HOME/Applications/Roblox.app/Contents/MacOS/RobloxPlayerInstaller.app" >/dev/null 2>&1
    echo -e "${GREEN}Enjoy the Opiumware experience! Please report bugs, issues or crashes that you discover.${NC}"
    echo -e "${GREEN}Launch Roblox from: $HOME/Applications/Roblox.app and Opiumware from: $HOME/Applications/Opiumware.app${NC}"
    echo -e "${YELLOW}This is detected. Consider using a alt.${NC}"
    open "$HOME/Applications/Roblox.app"
    open "$HOME/Applications/Opiumware.app"
    exit
}

main
